nname: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/ubuntu/VERTESA
            git pull origin main
            docker stop vertesa-container || true
            docker rm vertesa-container || true
            docker build -t vertesa-app .
            docker run -d -p 80:80 --name vertesa-container vertesa-app
